/**
 * calendar.js
 * Generates an .ics file for the upcoming Sat–Sun learning weekend.
 * This gets attached to the email so the recipient can import it
 * directly into Google Calendar, Apple Calendar, or Outlook.
 */

import { createHash } from 'crypto';

/**
 * Get the upcoming Saturday from today.
 */
function getUpcomingSaturday() {
  const now = new Date();
  const day = now.getDay(); // 0=Sun, 6=Sat
  const daysUntilSat = day === 6 ? 7 : (6 - day);
  const sat = new Date(now);
  sat.setDate(now.getDate() + daysUntilSat);
  sat.setHours(9, 0, 0, 0);
  return sat;
}

/**
 * Format a Date to iCal DTSTART format (local, no Z suffix for all-day awareness)
 */
function toIcalDate(date) {
  const pad = n => String(n).padStart(2, '0');
  return [
    date.getFullYear(),
    pad(date.getMonth() + 1),
    pad(date.getDate()),
    'T',
    pad(date.getHours()),
    pad(date.getMinutes()),
    pad(date.getSeconds())
  ].join('');
}

/**
 * Fold long lines per RFC 5545 (max 75 chars per line)
 */
function foldLine(line) {
  if (line.length <= 75) return line;
  const chunks = [];
  let remaining = line;
  while (remaining.length > 75) {
    chunks.push(remaining.slice(0, 75));
    remaining = ' ' + remaining.slice(75);
  }
  if (remaining) chunks.push(remaining);
  return chunks.join('\r\n');
}

/**
 * Escape special characters in iCal text values
 */
function icalEscape(str) {
  return String(str)
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '');
}

/**
 * Generate a deterministic UID from brief metadata
 */
function generateUID(brief) {
  const hash = createHash('md5')
    .update(brief.weekOf + brief.generatedAt)
    .digest('hex')
    .slice(0, 16);
  return `tech-strategist-${hash}@weekly-brief`;
}

/**
 * Build the full iCal event description from the brief
 */
function buildDescription(brief) {
  const lines = [
    `🗓 ${brief.weekOf}`,
    `⚡ ${brief.picks.length} Tech Picks | ~${Math.round(brief.totalHours)}h Total`,
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    'PICKS THIS WEEK',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    ''
  ];

  brief.picks.forEach((p, i) => {
    lines.push(`${i + 1}. ${p.name} [${p.priorityScore}/10] — ${p.domain}`);
    lines.push(`   ${p.tagline}`);
    lines.push(`   📅 Friday: ${p.plan?.friday?.read || 'Read docs + setup'}`);
    lines.push(`   🧠 Saturday: ${p.plan?.saturday?.tutorial || 'Deep learning day'}`);
    lines.push(`   🏗 Sunday: Build "${p.plan?.sunday?.project || 'Micro-project'}"`);
    lines.push(`   🔗 ${p.resource?.url || ''}`);
    lines.push('');
  });

  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('SCHEDULE');
  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  lines.push('');

  brief.picks.forEach(p => {
    lines.push(`📌 ${p.name}`);
    lines.push(`   Fri night (30 min): ${p.plan?.friday?.install || 'Setup'}`);
    lines.push(`   Sat (4h): ${p.plan?.saturday?.concepts?.join(', ') || 'Core concepts'}`);
    lines.push(`   Sun (4h): ${p.plan?.sunday?.steps?.[0] || 'Build project'}`);
    lines.push(`   🎯 Outcome: ${p.outcome}`);
    lines.push('');
  });

  lines.push('Generated by Tech Strategist — Powered by Claude AI');

  return lines.join('\\n');
}

/**
 * Main: generates the .ics file content as a string
 */
export function createCalendarEvent(brief) {
  const saturday = getUpcomingSaturday();
  const sunday   = new Date(saturday);
  sunday.setDate(saturday.getDate() + 1);

  // Saturday: 9am–9pm learning block
  const satStart = new Date(saturday); satStart.setHours(9, 0, 0, 0);
  const satEnd   = new Date(saturday); satEnd.setHours(21, 0, 0, 0);

  // Sunday: 9am–9pm build block
  const sunStart = new Date(sunday); sunStart.setHours(9, 0, 0, 0);
  const sunEnd   = new Date(sunday); sunEnd.setHours(21, 0, 0, 0);

  const now      = new Date();
  const uid1     = generateUID(brief) + '-sat';
  const uid2     = generateUID(brief) + '-sun';
  const dtstamp  = toIcalDate(now);

  const picksSummary = brief.picks.map(p => p.name).join(' · ');

  const satTitle = `🧠 Tech Learning Day — ${picksSummary}`;
  const sunTitle = `🏗 Tech Build Day — ${picksSummary}`;

  const description = buildDescription(brief);

  const calendar = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Tech Strategist//Weekly Brief//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:Tech Strategist',
    'X-WR-TIMEZONE:' + (process.env.TIMEZONE || 'Asia/Kolkata'),

    // ── Saturday Event ──
    'BEGIN:VEVENT',
    foldLine('UID:' + uid1),
    foldLine('DTSTAMP:' + dtstamp),
    foldLine('DTSTART:' + toIcalDate(satStart)),
    foldLine('DTEND:' + toIcalDate(satEnd)),
    foldLine('SUMMARY:' + icalEscape(satTitle)),
    foldLine('DESCRIPTION:' + description),
    foldLine('CATEGORIES:Learning,Technology,Dev'),
    'STATUS:CONFIRMED',
    'TRANSP:OPAQUE',
    'BEGIN:VALARM',
    'ACTION:DISPLAY',
    'DESCRIPTION:Tech learning day starts now!',
    'TRIGGER:-PT30M',
    'END:VALARM',
    'END:VEVENT',

    // ── Sunday Event ──
    'BEGIN:VEVENT',
    foldLine('UID:' + uid2),
    foldLine('DTSTAMP:' + dtstamp),
    foldLine('DTSTART:' + toIcalDate(sunStart)),
    foldLine('DTEND:' + toIcalDate(sunEnd)),
    foldLine('SUMMARY:' + icalEscape(sunTitle)),
    foldLine('DESCRIPTION:' + description),
    foldLine('CATEGORIES:Building,Technology,Dev'),
    'STATUS:CONFIRMED',
    'TRANSP:OPAQUE',
    'BEGIN:VALARM',
    'ACTION:DISPLAY',
    'DESCRIPTION:Time to build your weekend project!',
    'TRIGGER:-PT30M',
    'END:VALARM',
    'END:VEVENT',

    'END:VCALENDAR'
  ].join('\r\n');

  return calendar;
}
